### ISSUE TITLE
lfs failed

### ISSUE THREAD

**Issue by gameisbest** [gangashman/Ganga-RTS#1]
Downloading Assets/Models/units/knight/knight.blend (4.0 MB)
Error downloading object: Assets/Models/units/knight/knight.blend (a5b4aad): Smudge error: Error downloading Assets/Models/units/knight/knight.blend (a5b4aada7bb3af3f5ca8db31eeefd8b144606ae8329a2267173e6b5152a00d1e): batch response: This repository is over its data quota. Purchase more data packs to restore access.

Errors logged to D:\git\Ganga-RTS\.git\lfs\logs\20190529T161624.6568394.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Assets/Models/units/knight/knight.blend: smudge filter lfs failed

**Comment by gameisbest** [comment]
could you help me,thanks

**Comment by honnisha** [comment]
Hi. The size of the repository exceeds the free rate and git turn off lfs option. I will remove the excess soon.

**Comment by gameisbest** [comment]
thanks very much,hope can update soon

**Comment by honnisha** [comment]
Fixed
